name: Dotnet Build-Test-MSDeploy your project

on:
  push:
    branches: [ master ]

jobs:

  Build-Test-Deploy:
    runs-on: windows-latest


    steps:
    - name: Setup .NET Core
      uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: 'BlazorApp'
        msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
        msdeploy-username: ${{ secrets.MSDEPLOY_USERNAME }}
        msdeploy-password: ${{ secrets.MSDEPLOY_PASSWORD }}
        source-path: ${{ github.workspace }}\website\publish

