- name: IIS Deploy
  # You may pin to the exact commit or the version.
  # uses: ChristopheLav/iis-deploy@3b6a141da6e1923a4af25e01734ab58c081f8444
  uses: ChristopheLav/iis-deploy@v1.0.0
  with:
    # IIS website name
    website-name: ${{ secrets.IIS_WEBSITE_NAME }}
    # MS Deploy Service URL
    msdeploy-service-url: ${{ secrets.IIS_WEBSITE_NAME }}
    # Username used by Basic authentication to the MS Deploy Service
    msdeploy-username: ${{ secrets.IIS_WEBSITE_NAME }}
    # Password used by Basic authentication to the MS Deploy Service
    msdeploy-password: ${{ secrets.IIS_WEBSITE_NAME }}
    # The path to the source directory that will be deployed
    source-path: ${{ secrets.IIS_WEBSITE_NAME }}
